# Change these first
owner: calindra # Your GitHub organization or username, where this repository lives
repo: eitri-upptime # The name of this repository

sites:
  - name: C&A Prod
    url: https://api.eitri.tech/eitri-manager-api/o/environments/37c66d3b-f88c-44b1-b0a9-7b3adabf968e/configure
    maxResponseTime: 5000
  - name: C&A Dev
    url: https://api.eitri.tech/eitri-manager-api/o/environments/09083bb9-3aeb-45dc-8581-5614cd120820/configure
    maxResponseTime: 5000
  - name: Calindra Prod
    url: https://api.eitri.tech/eitri-manager-api/o/environments/956b5a02-6615-49b7-872b-a5c18d1a0748/configure
    maxResponseTime: 5000
  - name: Calindra Dev
    url: https://api.eitri.tech/eitri-manager-api/o/environments/6430bc21-7068-4811-a627-b183afa6fd0a/configure
    maxResponseTime: 10000
  - name: Toymania Prod
    url: https://api.eitri.tech/eitri-manager-api/o/environments/a3388e1f-d6ab-4ddc-a5a7-92c2b8e0fb36/configure
    maxResponseTime: 5000
  - name: Toymania Dev
    url: https://api.eitri.tech/eitri-manager-api/o/environments/9804b891-8024-44d2-82d1-26d19e33d5b6/configure
    maxResponseTime: 5000
  - name: Scolados Prod
    url: https://api.eitri.tech/eitri-manager-api/o/environments/0cd805d6-e728-4a51-a356-b2d716cf364e/configure
    maxResponseTime: 5000
  - name: Scolados Dev
    url: https://api.eitri.tech/eitri-manager-api/o/environments/292d923b-3fde-4978-97d0-912ae3209fe2/configure
  - name: Canal Dev
    url: https://api.eitri.tech/eitri-manager-api/o/environments/f7cfafbf-2088-46ef-b6d9-12d562c0d5fd/configure
  - name: Canal Prod
    url: https://api.eitri.tech/eitri-manager-api/o/environments/cc6d2570-7ec8-4577-8da2-fa9f2dab8ad1/configure
    maxResponseTime: 5000
  - name: Foundry
    url: https://api.eitri.tech/foundry/health
    maxResponseTime: 5000
  - name: Runes Foundry
    url: https://api.eitri.tech/runes-foundry/health
    maxResponseTime: 5000
  - name: Blind Guardian
    url: https://api.eitri.tech/blind-guardian-api/health
    maxResponseTime: 5000
  - name: Eitri Manager API
    url: https://api.eitri.tech/eitri-manager-api/health
    maxResponseTime: 5000
  - name: Mini Log
    url: https://api.eitri.tech/mini-log/health
    maxResponseTime: 5000
  - name: Vegvisir
    url: https://api.eitri.tech/eitri-vegvisir-api/health
    maxResponseTime: 5000
  - name: Share API
    url: https://api.eitri.tech/share-api/health
    maxResponseTime: 5000
  - name: Push Notification
    url: https://api.eitri.tech/push-notification-eitri-shop-api/health
    maxResponseTime: 5000
  - name: Valkyrie API
    url: https://api.eitri.tech/eitri-valkyrie-api/health
    maxResponseTime: 5000
  - name: Analytics
    url: https://api.eitri.tech/analytics/health
    maxResponseTime: 5000
  - name: Eitri-Doctor (v2.6.2) Release
    url: https://release.eitri.calindra.com.br/build/organizations/cf5660ee-bf90-42cd-9a43-9d2c69ee3c89/applications/749d6f6f-f10f-4448-b36e-9c484b1293b8/eitri-apps/eitri-doctor/2.6.2/environment/57765091-4dc1-4341-a24b-6a5658a9fe52/index.html
    maxResponseTime: 5000

  # - name: IPv6 test
  #   url: forwardemail.net
  #   port: 80
  #   check: "tcp-ping"
  #   ipv6: true
delay: 1000 # 1 seconds
assignees:
  - fabiooshiro
  - lucassdr
  - gbfonseca

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /eitri-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/30 * * * *"